site_name: DQC toolkit
repo_url: https://github.com/sumanthprabhu/DQC-Toolkit
site_url: https://sumanthprabhu.github.io/DQC-Toolkit/
site_author: Sumanth Prabhu
nav:
  - DQC toolkit: index.md
  - API Documentation:
      - Cross Validation based Curation: api/crossval.md
      - Util: api/util/utils.md
theme:
  name: material
  logo: images/dqc-toolkit-favicon.svg
  favicon: images/dqc-toolkit-favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - deduplicate-toc
  - attr_list

plugins:
  - mkdocstrings
  - search
  - mike

extra:
  version:
    provider: mike
    
copyright: Copyright &copy; 2024 Maintained by <a href="https://github.com/sumanthprabhu">Sumanth Prabhu</a>